apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
spec:
  dnsNames:
  - decodedpenguin.com
  - www.decodedpenguin.com
  secretName: penguin-tls-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
