apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: maciej.kopec92@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod 
    solvers:
    - http01:
       ingress: 
        class: traefik
